# Generated by Django 2.1.5 on 2020-03-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=30, null=True)),
                ('images', models.ImageField(upload_to='events')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
