# Generated by Django 2.2.7 on 2020-03-03 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragents',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='touragents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
