# Generated by Django 2.2.7 on 2019-11-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
